version: "3.5"
services:
  my-home:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-home:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=test"